name: "this is first GA WF"
on: push
jobs:
    myfrst:
        runs-on: ubuntu-latest
        steps:
          - name: myfrststep
            run: echo "Hello world" 
    mysecond:
        runs-on: ubuntu-latest
        steps:
            - name: second
              run: |
                echo "i will pass"       
            - name: final
              run: echo "Hello Bye"