name: wf gh events
on:
    push:
    pull_request: 
    workflow_dispatch: 
    schedule:
        - cron: '0/1 * * * *'
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
          - name: ent
            run: echo "the event is triggered by ${{ github.event_name }}"



